# Not to do List api
@baseURL=http://localhost:8000/api/v1/users
### GET the taks list
GET {{baseURL}}
 

 
### POST the tasks list
POST {{baseURL}}
Content-Type: application/json

{
"task":"sleep",
"hours":34
}


### Delete the taks list
DELETE  {{baseURL}}/6a7635d2f4fe481645f9e7cf

### Update the taks list
# PUT {{baseURL}}/1
# Content-Type: application/json

# {
#     "housr":20
# }

PATCH {{baseURL}}
Content-Type: application/json

{
    "_id":"6a7637304f13b41ac2d4259a",
    "task":"study",
    "housr":15,
    "type":"bad"
}