# Not to do List api
@baseURL=http://localhost:8000/api/v1/users
### GET the taks list
GET {{baseURL}}
 

 
### POST the tasks list
POST {{baseURL}}
Content-Type: application/json

{
"task":"shopping",
"hours":20,
"type":"bad"
}


### Delete the taks list
DELETE  {{baseURL}}/6a762b24adf0a02eb8dc2387

### Update the taks list
# PUT {{baseURL}}/1
# Content-Type: application/json

# {
#     "housr":20
# }

PATCH {{baseURL}}
Content-Type: application/json

{
    "_id":"6a762b24adf0a02eb8dc2387",
    "housr":15,
    "type":"bad"
}